;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-indent-new-comment-line
        c-up-conditional
        comment-dwim
        cua-insert-char-rectangle
        cua-paste
        down-list
        eval-last-sexp
        fill-paragraph
        forward-sexp
        ido-execute-command
        kill-region
        kill-sexp
        mark-sexp
        next-error
        nxml-electric-slash
        org-force-self-insert
        smex
        sp--self-insert-command
        sp-cua-replace-region
        sp-self-insert-command
        wdired-finish-edit
        yas-expand
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        ff-find-related-file
        minimap-toggle
        query-replace
        sacha/search-word-backward
        sacha/search-word-forward
        ))
