;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anchored-transpose
        backward-sexp
        backward-up-list
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-up-conditional
        comment-dwim
        cua-insert-char-rectangle
        cua-paste
        down-list
        eval-last-sexp
        fill-paragraph
        forward-sexp
        ido-execute-command
        indent-for-tab-command
        kill-region
        kill-sexp
        mark-sexp
        my-move-forward-list
        next-error
        nxml-electric-slash
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        smex
        sp--self-insert-command
        sp-cua-replace-region
        sp-self-insert-command
        stp-decorate-atomic
        stp-decorate-shared-ptr
        wdired-finish-edit
        yas-expand
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        ff-find-related-file
        minimap-toggle
        repeat
        sacha/search-word-backward
        sacha/search-word-forward
        undefined
        wgrep-change-to-wgrep-mode
        wgrep-finish-edit
        widget-button-click
        ))
